### ISSUE TITLE
Purge Tailwind for base-2021

### ISSUE THREAD

**Issue by madc** [bolt/themes#64]
I just started building a bolt theme using tailwind and  invested some research in purging/minimizing the css. I described the current state here: https://github.com/bolt/project/issues/51#issuecomment-872821096

The tailwind setup should be part of the 2021 theme as it is a starting point for many developers. Let me know if that makes sense, I'd be willing to prepare a PR once my setup is "finished" and better tested.

**Comment by bobdenotter** [comment]
@madc Yes, that'd be most appreciated! 👍
